name: Secrets usage sample
on:
  push:
    6_secrets_usage

jobs:
  macos:
    name: Secret usage
    runs-on: macos-latest
    steps:
      - name: Print secret
        run: echo "I am a secret, you won't see me haha. Secret - ${{ secret.TEST_SECRET }}"